<?php
use Drupal\Core\Routing\RouteMatchInterface;

function migrate_training_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_training module.
    case 'help.page.migrate_training':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration Training') . '</p>';
      return $output;

    default:
  }
}
